[package]
name = "adieu"
version = "0.1.0"
authors = ["Ruin0x11 <ipickering2@gmail.com>"]
edition = "2018"

[dependencies]
avg32 = { path = "../avg32" }
serde = "1.0.117"
serde_derive = "1.0.117"
anyhow = "1.0"
lexpr = "0.2.5"
serde-lexpr = "0.1.1"

[dev-dependencies]
pretty_assertions = "0.6.1"
